### ISSUE TITLE
View "Advanced Statistics" tab without Super Admin permission and "Change Settings" tab.

### ISSUE THREAD

**Issue by juanchopl87** [bramley/phplist-plugin-statistics#13]
View the "Advanced Statistics" tab without Super Admin permission and without the "Change Settings" tab.

![imagen](https://user-images.githubusercontent.com/115455886/194825167-9fdc2e66-827c-4917-9a9a-a24f8d33d9e1.png)

![imagen](https://user-images.githubusercontent.com/115455886/194825279-3399deea-601b-46b3-8b76-807daba77106.png)

Is there any way to view the tab without having these permissions enabled?

Thank you very much

**Comment by bramley** [comment]
phplist restricts plugin pages in the navigation menu to super-admins only, see
https://github.com/phpList/phplist3/blob/0b0c27b49fba861dc8cf431ea340c1644e36d6f9/public_html/lists/admin/connect.php#L1076

But you can kind of work-around that by adding `&pi=MessageStatisticsPlugin` to the phplist URL. That should display a page which has a  link to the plugin's main page. The plugin should display only those campaigns owned by that ordinary admin but I haven't looked at that for a long time.
