### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by damanic** [bramley/phplist-plugin-statistics#5]
Thanks for the plugin. 

Issue that I have: Campaigns, Lists, Subscribers are managed by an administrator account. I want to set up a new user account to give access to statistics but not allow them to create lists, campaigns etc. If I create a user and assign only the permission 'View Statistics' they cannot see any because all the activity is owned by the 'Admin' account.

Is it possible for your plugin to open up statistics to other user accounts that do not 'own' the campaign/list ? Perhaps by extending the permissions in PHPLIST or just adding an additional config attribute in your plugin that allows all users with the  'View Statistics' privilege to see all statistics regardless of owner?

**Comment by bramley** [comment]
I have had a look into this and the simplest solution is for you to modify one line in the plugin code.
In file Model.php  change line 92 from

    $this->access = accessLevel('mviews');
to

    $this->access = 'all';

That should allow an ordinary admin to view statistics of all campaigns.

**Comment by damanic** [comment]
Excellent, thanks. 

Can you make the plugin so it is only accessible when an administrator has the 'View statistics' privilege?
```
if($_SESSION['privileges'] ['statistics]){}
```

Also if you can add a config option for 'owner only' statistics that can be toggled on/off - that would be great too. Using a config file in the pluging dir looks like a simple solution.  I can't see an easy way to add new administrator privileges.
```
$this->access = $stats_config['owner_only'] ? 'owner' : 'all'
```

**Comment by bramley** [comment]
I did look at those ideas previously but feel that they should be implemented in core phplist, not in a plugin.
