### ISSUE TITLE
FR: Sign-up Page Stats

### ISSUE THREAD

**Issue by justinputney** [bramley/phplist-plugin-statistics#6]
This is brilliant! I love that I can see things at a glance now!

One more tab that I'd love to see is for subscribe pages. I have multiple subscribe pages and I plan to add more. With some, I give away free tools. I also want to set up custom subscribe pages for autoresponder lists. I'd love to compare the traction that the different sign-up pages get.

**Comment by bramley** [comment]
This plugin provides statistics on campaigns. What you are describing might be better placed within the Subscribers plugin https://github.com/bramley/phplist-plugin-subscribers

**Comment by justinputney** [comment]
Aha, sorry about that. I'm also using that wonderful plugin. I'll re-post the request with the subscriber plugin for tracking purposes.
