### ISSUE TITLE
set date range for CSV export

### ISSUE THREAD

**Issue by jbenicky** [bramley/phplist-plugin-statistics#7]
Hi,
first of all thank you for perfect plugin. Would it be possible to implement some kind of filter to set date range for CSV export? We have really many campains and we don't need full export all the time. Something like "last month" or manual setting of date range would be perfect. Thank you.

**Comment by bramley** [comment]
I don't want to add a date selection field for the export. Instead I have added a configuration setting to export either all messages or only those displayed. You can then display 10 or 25 messages to cover those that you want to export. You can also modify the page url directly to have any other value for the show parameter.

**Comment by jbenicky** [comment]
Yes, that would be also beneficial. Thank you.

**Comment by bramley** [comment]
I forgot to point out that there is a new version of CommonPlugin that has also be updated.
