### ISSUE TITLE
Extract never ever unopened all campaign email adddresses

### ISSUE THREAD

**Issue by facilitator999** [bramley/phplist-plugin-statistics#8]
We want to remove subscribers who have never ever opened a single email from us, currently its limited to one campaign

**Comment by bramley** [comment]
You can use the Subscribers plugin https://resources.phplist.com/plugin/subscribers#advanced_search. That displays a column showing the number of campaigns sent/opened/clicked by each subscriber. Export the results then open in a spreadsheet and filter those who have not opened any campaigns.

**Comment by facilitator999** [comment]
unfortunately this guide does not produce enough info to extract the data i need

**Comment by facilitator999** [comment]
OH... i managed to get it to work. thank you so much
