### ISSUE TITLE
Active Campaigns not showing

### ISSUE THREAD

**Issue by Sirila** [bramley/phplist-plugin-statistics#9]
Hello,
Is it normal that campaigns with status "Activ" don't show under
Statistics -> Advanced Statistics -> Campaigns ?
The campaign in question has a "Stop sending after" value couple of days ahead and "Requeue every day" until the "Stop sending after" value.

phplist configuration:
PHP 5.6
PHPList version 3.3.1
CommonPlugin version3.6.1+20170414
Campaign Statistics version2.1.10+20170418

**Comment by bramley** [comment]
The plugin selects only campaigns with status 'sent', 'inprocess' and 'suspended'. I guess that your campaign is 'submitted'. Usually a submitted campaign has not yet been sent so will have no opens or clicks, but that is not the case when it is requeued.

You can try changing one line of code in the plugin to include 'submitted' status. 
File plugins/MessageStatisticsPlugin/DAO/Message.php

line 31 is
`    const MESSAGE_SELECT = "'sent', 'inprocess', 'suspended'";`

change that to 
`    const MESSAGE_SELECT = "'sent', 'inprocess', 'suspended', 'submitted'";`

**Comment by Sirila** [comment]
The suggestion made the submitted ("Activ") campaign appear.

In my particular case the campaign is already sent and shows statistics.
Probably because of the "Requeue" enabled option the status stays 'submitted'.

Thank you bramley!
